// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akzwyivnlcuieipbzshk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrend5aXZubGN1aWVpcGJ6c2hrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NjEzMTYsImV4cCI6MjA3MzEzNzMxNn0.u22S116rdNlhe2HfGMHfek7dYnfph7Ea5gaJ7mz7Eko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});